/*
Lambda Expression (LE)
======================
Q1) What is a LE?
	- A LE is an anonymous function
	  means it is a nameless function

	- A LE is an implementation of one FI

	- A LE is an object which is an instance of 
	 one functional interface implementation

Q2) Why LE?
	1. for enabling FP in Java and also 
    2. for implementing a FI with less code
    3. for passing a function directly as an argument 
	   to a method without creating extra class, method and object
	 
Q3) Syntax for creating LE?
	- A LE has two parts 
			1. parameters and
			2. body with logic
	           connected an lambda operator [->]

	- (parameters) -> {logic}; 
	 
	- this '->' is called lambda operator
	- hence this expression is called lambda expression
	
	- A lambda operator '->' is a binary operator, 
	  it takes two operands () and {} 

Q4) How can we implement and store a LE?
	- by using a FI
	
	- with a FI only we can create and store a LE
	- The target type for creating and storing a LE is FI

Q5) What is the internal name, parameters, return type and exception of a LE?
	- Those are derived from FI
	
	- Generally people say 
	  A LE can have 
		0-n number of parameters
		any return type and 
		can throw any exception
	  it is a wrong statements

	- all above things are derived from a FI 
	  to which this LE is assigned.
	 
Q6) When there is no name to the LE, how can we execute its logic?
	- The LE name is same as FI method name
	- Hence, we must call LE by using FI method name
	  by passing arguments according to the FI method parameters
	 
Q7) What is the complete syntax for creating and calling a LE?
		FI fi = (parameters) -> { logic } ;
		fi.method(args);

Q8) LE Short-cut syntaxes?
	FI fi = (params) -> { statements } ;

	FI fi = () 	-> stmt;   	//1. for one statement, { } is not required
	FI fi = (a) -> stmt;   	//2. for the parameter, type is not required
	FI fi =  a 	-> stmt;   	//3. for one parameter, () is not required
	FI fi = (a, b) 	-> stmt;//4. for zero or multiple parameters, () is required
	FI fi = (a, b) 	-> 50;	//5. we can return value directly, 
	                        //   { } and return kw are not required
         
Q9) Explain LE creation, calling and execution with 
    zero parameters, one parameter, multiple parameters 
	and with void and non-void return types
 */

public class Test06_LE {
	public static void main(String[] args) {
		
		//Rule: We can not place LE directly in a method
		//it leads to CE, because it is an expression, 
		//it must be assigned to a variable
			//(a, b) -> System.out.println(a + b); //CE: not a statement		
			
		//Because LE is an implementation of one FI
		//First we must create a FI
		//to create LE by implementing this FI method math operation
		
		System.out.println("Before LE");
	
		I11 i1 = () -> { System.out.println("I11 LE"); }; //function creation
		i1.m1();  //calling and executing LE
		System.out.println();
		
		I12 i2 = (int a) -> { System.out.println("I12 LE a: "+ a); }; //creation
		i2.m1(10); //calling
		i2.m1(20);
		System.out.println();
				
		I13 i3 = (int a, int b) -> { System.out.println("I13 LE result: "+ (a + b));}; 
		i3.m1(10, 20);
		i3.m1(30, 40);
		System.out.println();
				
		I14 i4 = () -> {
							System.out.println("I14 LE");
							return 10; 
					   };
		i4.m1();			
		int res = i4.m1();
		System.out.println(i4.m1());
		System.out.println();
		
		I15 i5 = (int a) -> {
								System.out.println("I15 LE");
								return a + 50;
							};
		i5.m1(10);					
		res = i5.m1(20);
		System.out.println(i5.m1(30));					
		System.out.println();
		
	//A LE is an object which is an instanceof FI implementation class
	//The Implementation class is generated by JVM at runtime dynamically 
		System.out.println(i1);
		System.out.println(i2);
		System.out.println(i3);
		System.out.println(i4);
		System.out.println(i5);
		
  //======================================================================
		I11 i11  = () -> { System.out.println("LE1"); };	
		I11 i111 = () ->   System.out.println("LE1"); 
		
		I12 i12  = (int a) -> { System.out.println("LE2");};
		I12 i121 = (int a) ->   System.out.println("LE2");
		I12 i122 = (a)     ->   System.out.println("LE2");
		I12 i123 = a       ->   System.out.println("LE2");
		
		I13 i13  = (int a, int b) -> { System.out.println("LE3");};
		I13 i131 = (a, b)         ->   System.out.println("LE3");
		
		I14 i14  = () -> { return 50; };
		I14 i141 = () ->   50;
		I14 i142 = () ->   50 + 60;
		I14 i143 = () ->   "abc".length();
		
		I15 i15 = (int a) -> {return a + 50;}; 
		I15 i151 = a      ->  a + 50;
		System.out.println("LE151 res: " + i151.m1(70));
  //=======================================================================		
/**/		
		System.out.println("After LE");
	}
}

@FunctionalInterface
interface I11{
	void m1();
}

@FunctionalInterface
interface I12{
	void m1(int a);
}

@FunctionalInterface
interface I13{
	void m1(int a, int b);
}

@FunctionalInterface
interface I14{
	int m1();
}

@FunctionalInterface
interface I15{
	int m1(int a);
}

@FunctionalInterface
interface I16<T>{
	T m1(T t);
}

@FunctionalInterface
interface I17<T, R>{
	R m1(T t);
}

@FunctionalInterface
interface I17<T>{
	T m1();
}

